pipeline {
    agent any
    environment {
        TFACTION = "apply"
        GCP_PROJECT_ID = 'gcp-cloudrun-nodejs-mysql-app'      
        GCP_CREDENTIALS = credentials('gcp-service-account-key') 
        GIT_CREDENTIALS_ID = 'git-credentials-id'
        // GIT_REPO_URL = 'https://github.com/anitamaharana55/NodejsApp_GCP.git'
        GIT_REPO_URL = 'https://github.com/UmeshBuraWissen/gcp-cloudrun-nodejs-mysql-infra.git'
        CLIENT_EMAIL='nodejsdemo@gcp-cloudrun-nodejs-mysql-app.iam.gserviceaccount.com'
    }
    stages {
        stage('Authenticate to GCP') {
            steps {
                // Using the GCP service account key as a secret file
                withCredentials([file(credentialsId: 'gcp-service-account-key', variable: 'GCP_KEY_FILE')]) {
                    script {

                        // Authenticate using the secret file path
                        sh 'gcloud auth activate-service-account --key-file=$GCP_KEY_FILE'
                        sh 'gcloud config set project ${GCP_PROJECT_ID}'
                        sh 'gcloud auth list'
                        sh 'gcloud config list'
                        
                    }
                }
            }
        }
        stage('Checkout Code') {
            steps {
                // Cloning the repository
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']],          
                    userRemoteConfigs: [[url: "${GIT_REPO_URL}", credentialsId: "${GIT_CREDENTIALS_ID}"]]
                ])
            }
        }
        stage('Install Checkov') {
            steps {
                script {
                    echo "Installing Checkov..."
                    sh '''
                        python3 -m venv venv  # Create virtual environment
                        ./venv/bin/pip install --upgrade pip 
                        ./venv/bin/pip install checkov 
                    '''
                }
            }
        }

        stage('Run Checkov') {
            steps {
                script {
                    echo "Running Checkov security scan on Terraform files..."
                    dir('GCP-CloudRun-Nodejs-Mysql-app') {
                        sh './venv/bin/checkov -d .'
                    }
                }
            }
        }
    }
}
        stage('Terraform Init') {
            steps {
                sh '''
                cd GCP-CloudRun-Nodejs-Mysql-infra
                    terraform init -reconfigure
                '''
        }
            }
        
        stage('Terraform Plan') {
            steps {
                sh '''
                cd GCP-CloudRun-Nodejs-Mysql-infra
                    terraform refresh
                    terraform plan
                '''
            }
        }
        stage('Terraform Apply or Destroy') {
            steps {
                sh '''
                cd GCP-CloudRun-Nodejs-Mysql-infra
                    terraform apply -auto-approve
                '''
            }
        }
    }
}
    